### ISSUE TITLE
Status of this application?

### ISSUE THREAD

**Issue by fred-wang** [jonnycrunch/ipfs-uri-scheme#2]
Hi, thanks for starting this registration to IANA. Can you please tell me what's the status here?  

See https://github.com/arewedistributedyet/arewedistributedyet/issues/28#issuecomment-624087520

**Comment by lidel** [comment]
@fred-wang afaik we didn't have the bandwidth to push this over the finish line:
it was not submitted yet.

@jonnycrunch wrote initial formal definition in https://github.com/jonnycrunch/ipfs-uri-scheme/blob/master/application.md#3-uri-scheme-registration, but other sections need to have _lorem ipsum_ replaced with actual text.


Potential sources: 
- https://github.com/ipfs/in-web-browsers/blob/master/ADDRESSING.md 
  – a quick addressing reference used when talking with Opera, Brave and other vendors

- https://docs-beta.ipfs.io/how-to/address-ipfs-on-web/ 
  – recently created docs for end users

**Comment by fred-wang** [comment]
@lidel Thanks. Checking the https://tools.ietf.org/html/rfc7595#section-7.4 ; it seems they simplified the amount of information required in the request (old provisional applications had many empty fields or "unknown use with care" anyway) so probably that can be a very minimal thing with only relevant references.

Can you please check this and tell me if that looks reasonable:
https://raw.githubusercontent.com/fred-wang/iana-uri-schemes-provisional-registration-requests/master/ipfs.txt
https://raw.githubusercontent.com/fred-wang/iana-uri-schemes-provisional-registration-requests/master/ipns.txt

**Comment by lidel** [comment]
@fred-wang both look good to me, thank you! :+1:

**Comment by fred-wang** [comment]
ipfs/ipns are now registered:
https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml
